Repository obss/sahi, pull requests merged in 2021-09, with the labels that each got.

#207 add docs for `cocoresult2fiftyone.py` script
  docs/SCRIPTS.md
Labels: documentation, enhancement

#208 convert scripts to cli commands
  .github/workflows/ci.yml
  .github/workflows/package_testing.yml
  README.md
  docs/CLI.md
  docs/SCRIPTS.md
  requirements.txt
  sahi/__init__.py
  sahi/cli.py
  sahi/predict.py
  sahi/prediction.py
  sahi/scripts/__init__.py
  sahi/scripts/coco2fiftyone.py
  sahi/scripts/coco2yolov5.py
  sahi/scripts/coco_error_analysis.py
  sahi/scripts/coco_evaluation.py
  sahi/scripts/predict.py
  sahi/scripts/predict_fiftyone.py
  sahi/scripts/slice_coco.py
  sahi/slicing.py
  sahi/utils/cv.py
  sahi/utils/file.py
  scripts/coco2yolov5.py
  scripts/cocoresult2fiftyone.py
  scripts/predict.py
  scripts/predict_fiftyone.py
  scripts/slice_coco.py
  setup.py
  tests/test_predict.py
Labels: documentation, enhancement, workflows

#209 fix cli docs
  docs/CLI.md
Labels: documentation, enhancement

#210 update readme
  README.md
Labels: documentation, enhancement

#211 add devrim to contributers
  README.md
Labels: documentation, enhancement

#217 Include requirements.txt in sdist
  MANIFEST.in
  requirements.txt
  setup.py
Labels: enhancement

#221 fix optional dependencies
  .github/workflows/ci.yml
  requirements.txt
  sahi/scripts/coco_error_analysis.py
  sahi/scripts/coco_evaluation.py
  sahi/utils/fiftyone.py
Labels: bug, enhancement

#219 move conda builds to conda-forge
  .github/workflows/publish_conda.yml
  README.md
  conda/conda_build_config.yaml
  conda/meta.yaml
  setup.py
Labels: enhancement

#223 fix a bug in coco2fiftyone
  sahi/__init__.py
  sahi/scripts/coco2fiftyone.py
Labels: bug, enhancement

#224 update docstring
  sahi/postprocess/combine.py
Labels: documentation, enhancement

#225 handle predictions with negative bbox values
  docs/COCO.md
  sahi/model.py
  sahi/utils/coco.py
Labels: documentation, enhancement

#227 fix `remove_invalid_coco_results`
  sahi/utils/coco.py
Labels: bug

#228 fix coco evaluation
  sahi/scripts/coco_evaluation.py
Labels: bug, enhancement

#230 handle when image name is very short in yolov5 conversion
  sahi/utils/coco.py
Labels: enhancement
