Repository obss/sahi, pull requests merged in 2022-06, with the labels that each got.

#465 Added support for exporting predictions in COCO format
  docs/coco.md
  sahi/utils/coco.py
  tests/test_cocoutils.py
Labels: documentation, enhancement

#479 update device priority for Detectron2DetectionModel
  sahi/model.py
Labels: enhancement

#481 fix pickle export for video
  sahi/predict.py
Labels: bug, enhancement

#484 refactor import and torch utils
  sahi/model.py
  sahi/utils/import_utils.py
  sahi/utils/torch.py
Labels: enhancement

#485 make detectionmodel classes more explicit in automodel
  sahi/auto_model.py
Labels: enhancement

#487 utilize check_requirements in several modules
  sahi/postprocess/combine.py
  sahi/predict.py
  sahi/utils/fiftyone.py
Labels: enhancement

#488 update package versions in workflows
  .github/workflows/ci.yml
  .github/workflows/ci_torch1.10.yml
  .github/workflows/package_testing.yml
  docs/mot.md
  sahi/utils/import_utils.py
  sahi/utils/mot.py
Labels: enhancement, workflows

#486 add torchvision detector support
  README.md
  demo/inference_for_torchvision.ipynb
  sahi/auto_model.py
  sahi/model.py
  sahi/utils/torchvision.py
  tests/data/models/torchvision/fasterrcnn_resnet50_fpn.yaml
  tests/data/models/torchvision/ssd300_vgg16.yaml
  tests/test_torchvision.py
Labels: enhancement

#494 remove legacy image_size parameter
  sahi/model.py
  sahi/predict.py
Labels: enhancement

#498 AutoDetectionModel can be imported from sahi
  sahi/__init__.py
Labels: enhancement

#489 add python3.6 support
  .github/workflows/ci.yml
  .github/workflows/ci_torch1.10.yml
  .github/workflows/package_testing.yml
  requirements.txt
  sahi/auto_model.py
  setup.py
  tests/test_huggingfacemodel.py
  tests/test_layer.py
  tests/test_predict.py
Labels: enhancement, workflows

#499 refactor exception handling
  sahi/annotation.py
  sahi/model.py
  sahi/predict.py
  sahi/scripts/coco_error_analysis.py
  sahi/scripts/coco_evaluation.py
  sahi/scripts/predict.py
  sahi/slicing.py
  sahi/utils/coco.py
  sahi/utils/mot.py
Labels: enhancement

#502 improve requirements and import handling
  docs/cli.md
  requirements.txt
  sahi/cli.py
  sahi/utils/fiftyone.py
  sahi/utils/import_utils.py
  sahi/utils/mot.py
  sahi/utils/torch.py
  sahi/utils/torchvision.py
  tests/test_detectron2.py
Labels: documentation, enhancement, cli

#503 add python 3.10 support
  .github/workflows/ci.yml
  setup.py
Labels: enhancement

#509 refactor automodel to lazyload models
  sahi/auto_model.py
Labels: enhancement

#510 update automodel loading method to from_pretrained
  sahi/auto_model.py
  sahi/predict.py
  sahi/scripts/predict.py
  tests/test_huggingfacemodel.py
  tests/test_predict.py
Labels: enhancement

#514 update predict verbose
  sahi/predict.py
Labels: bug
