Repository obss/sahi, pull requests merged in 2022-08, with the labels that each got.

#541 fix segmentation fault in same cases
  sahi/predict.py
Labels: bug, enhancement

#549 refactor requirement checking
  sahi/auto_model.py
  sahi/model.py
  sahi/postprocess/combine.py
  sahi/predict.py
  sahi/scripts/predict.py
  sahi/utils/import_utils.py
  sahi/utils/mot.py
  sahi/utils/torch.py
Labels: enhancement

#548 Code formatting and checks are moved to a single module.
  .github/workflows/ci.yml
  .github/workflows/ci_torch1.10.yml
  README.md
  scripts/run_code_style.py
  scripts/utils.py
  setup.cfg
  setup.py
Labels: enhancement

#553 fix a typo in type hinting
  sahi/slicing.py
Labels: documentation

#554 fix an incorrect url in comments
  sahi/utils/import_utils.py
Labels: documentation

#559 fix an incorrect url in comments
  README.md
Labels: documentation
