Repository obss/sahi, pull requests merged in 2022-09, with the labels that each got.

#574 fix auto slice warning
  README.md
  sahi/slicing.py
Labels: enhancement

#575 fix a slice_image error
  sahi/slicing.py
Labels: enhancement

#516 refactor demo notebooks by utilizing newly introduced AutoDetectionMo…
  demo/inference_for_detectron2.ipynb
  demo/inference_for_huggingface.ipynb
  demo/inference_for_mmdetection.ipynb
  demo/inference_for_torchvision.ipynb
  demo/inference_for_yolov5.ipynb
  sahi/auto_model.py
  sahi/model.py
Labels: documentation, enhancement

#603 update workflow versions
  .github/workflows/ci.yml
  .github/workflows/ci_torch1.10.yml
  .github/workflows/package_testing.yml
  .github/workflows/publish_pypi.yml
Labels: enhancement, workflows
