Repository obss/sahi, pull requests merged in 2022-10, with the labels that each got.

#676 flake8 dependency fix for python3.7.
  setup.py
Labels: bug

#689 fix links in readme
  README.md
Labels: documentation

#692 remove layer support
  .github/workflows/ci.yml
  .github/workflows/ci_torch1.10.yml
  .github/workflows/package_testing.yml
  docs/cli.md
  sahi/auto_model.py
  sahi/utils/import_utils.py
  tests/test_layer.py
Labels: enhancement

#691 Fixed a bug in greedynmm func
  sahi/postprocess/combine.py
  tests/test_huggingfacemodel.py
  tests/test_predict.py
  tests/test_torchvision.py
Labels: bug, enhancement
