Repository obss/sahi, pull requests merged in 2024-05, with the labels that each got.

#988 Improve yolov8 config
  sahi/models/yolov8.py
Labels: bug

#1036 disable slice export by default
  sahi/predict.py
Labels: enhancement

#1037 remove quality param in slice export due to errors
  sahi/slicing.py
Labels: bug, enhancement
