Repository obss/sahi, pull requests merged in 2025-06, with the labels that each got.

#1164 Remove deepsparse integration
  .gitignore
  README.md
  demo/inference_for_sparse_yolov5.ipynb
  docs/README.md
  docs/predict.md
  pyproject.toml
  sahi/auto_model.py
  sahi/models/yolov5sparse.py
  sahi/scripts/coco_error_analysis.py
  sahi/scripts/coco_evaluation.py
  sahi/utils/sparseyolov5.py
  tests/check_dependencies.sh
  tests/test_sparseyolov5model.py
  uv.lock
Labels: documentation, enhancement, workflows, cli

#1091 add TensorrtExecutionProvider to yolov8onnx
  sahi/models/yolov8onnx.py
Labels: enhancement

#1161 Add new framework Roboflow (RFDETR models)
  README.md
  demo/inference_for_roboflow.ipynb
  sahi/auto_model.py
  sahi/models/roboflow.py
  tests/test_roboflow.py
Labels: documentation, enhancement

#1175 add new contributors to readme
  README.md
Labels: documentation

#1180 fix: Update inference method to use 'threshold' instead of 'confidence'
  sahi/models/roboflow.py
Labels: bug, enhancement

#1179 Update README.md
  README.md
Labels: documentation, enhancement

#1181 improve pyproject.toml
  pyproject.toml
Labels: documentation, enhancement

#1183 Refactor dependency managment and some docs
  .github/workflows/ci.yml
  .github/workflows/ruff.yaml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  README.md
  pyproject.toml
  sahi/scripts/coco_error_analysis.py
  sahi/scripts/coco_evaluation.py
  sahi/utils/torch.py
  sahi/utils/yolov8onnx.py
  scripts/format_code.py
  scripts/run_code_style.py
  scripts/utils.py
Labels: documentation, enhancement, workflows, cli

#1182 update torchvision support to latest api
  .github/workflows/ci.yml
  sahi/models/torchvision.py
  sahi/utils/torchvision.py
  tests/test_torchvision.py
Labels: enhancement
